### PR TITLE
Upgrade Coil to 2.0.0-alpha06

### PR DESCRIPTION
**Pull request by msfjarvis**
Raising as draft since this will be needed upstream sooner than later and I had already done the work

### CODE REVIEW

**Comment by MoveUpwardsDev** [comment]
Any chance this can be merged and released as an alpha ?

**Comment by halilozercan** [comment]
I'm sorry I forgot about this. To be honest I didn't really pay attention because it was created as a draft PR. If it were to be created as a final PR, I would have merged it.

**Comment by msfjarvis** [comment]
> I'm sorry I forgot about this. To be honest I didn't really pay attention because it was created as a draft PR. If it were to be created as a final PR, I would have merged it.

I raised it as a draft since I was unsure what the policy would be around depending on an alpha release of Coil. If it's not a problem then feel free to review and merge.

**Comment by MoveUpwardsDev** [comment]
@halilozercan do you think you can review this PR and if you agree to merge it, maybe release an alpha version of your lib ?

**Comment by MoveUpwardsDev** [comment]
Thanks ! ❤️

**Pull request merged**
